name: Code Quality

on:
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better analysis

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, python
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Check for TODOs and FIXMEs
        run: |
          echo "Scanning for TODOs and FIXMEs..."
          grep -r "TODO\|FIXME" backend frontend --exclude-dir=node_modules --exclude-dir=dist --exclude-dir=__pycache__ || echo "No TODOs or FIXMEs found"
        continue-on-error: true
